// Code generated by ent, DO NOT EDIT.

package instance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/logan/cloudcode/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldProvider, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldProviderID, v))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldHost, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v int) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldPort, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldStatus, v))
}

// VolumeID applies equality check predicate on the "volume_id" field. It's identical to VolumeIDEQ.
func VolumeID(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldVolumeID, v))
}

// NetbirdConfig applies equality check predicate on the "netbird_config" field. It's identical to NetbirdConfigEQ.
func NetbirdConfig(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldNetbirdConfig, v))
}

// AgentSecret applies equality check predicate on the "agent_secret" field. It's identical to AgentSecretEQ.
func AgentSecret(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldAgentSecret, v))
}

// LastActivityAt applies equality check predicate on the "last_activity_at" field. It's identical to LastActivityAtEQ.
func LastActivityAt(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldLastActivityAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldProvider, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldProviderID, vs...))
}

// ProviderIDGT applies the GT predicate on the "provider_id" field.
func ProviderIDGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldProviderID, v))
}

// ProviderIDGTE applies the GTE predicate on the "provider_id" field.
func ProviderIDGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldProviderID, v))
}

// ProviderIDLT applies the LT predicate on the "provider_id" field.
func ProviderIDLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldProviderID, v))
}

// ProviderIDLTE applies the LTE predicate on the "provider_id" field.
func ProviderIDLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldProviderID, v))
}

// ProviderIDContains applies the Contains predicate on the "provider_id" field.
func ProviderIDContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldProviderID, v))
}

// ProviderIDHasPrefix applies the HasPrefix predicate on the "provider_id" field.
func ProviderIDHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldProviderID, v))
}

// ProviderIDHasSuffix applies the HasSuffix predicate on the "provider_id" field.
func ProviderIDHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldProviderID, v))
}

// ProviderIDEqualFold applies the EqualFold predicate on the "provider_id" field.
func ProviderIDEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldProviderID, v))
}

// ProviderIDContainsFold applies the ContainsFold predicate on the "provider_id" field.
func ProviderIDContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldProviderID, v))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldHost, v))
}

// HostIsNil applies the IsNil predicate on the "host" field.
func HostIsNil() predicate.Instance {
	return predicate.Instance(sql.FieldIsNull(FieldHost))
}

// HostNotNil applies the NotNil predicate on the "host" field.
func HostNotNil() predicate.Instance {
	return predicate.Instance(sql.FieldNotNull(FieldHost))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldHost, v))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v int) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v int) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...int) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...int) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v int) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v int) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v int) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v int) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldPort, v))
}

// PortIsNil applies the IsNil predicate on the "port" field.
func PortIsNil() predicate.Instance {
	return predicate.Instance(sql.FieldIsNull(FieldPort))
}

// PortNotNil applies the NotNil predicate on the "port" field.
func PortNotNil() predicate.Instance {
	return predicate.Instance(sql.FieldNotNull(FieldPort))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldStatus, v))
}

// VolumeIDEQ applies the EQ predicate on the "volume_id" field.
func VolumeIDEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldVolumeID, v))
}

// VolumeIDNEQ applies the NEQ predicate on the "volume_id" field.
func VolumeIDNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldVolumeID, v))
}

// VolumeIDIn applies the In predicate on the "volume_id" field.
func VolumeIDIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldVolumeID, vs...))
}

// VolumeIDNotIn applies the NotIn predicate on the "volume_id" field.
func VolumeIDNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldVolumeID, vs...))
}

// VolumeIDGT applies the GT predicate on the "volume_id" field.
func VolumeIDGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldVolumeID, v))
}

// VolumeIDGTE applies the GTE predicate on the "volume_id" field.
func VolumeIDGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldVolumeID, v))
}

// VolumeIDLT applies the LT predicate on the "volume_id" field.
func VolumeIDLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldVolumeID, v))
}

// VolumeIDLTE applies the LTE predicate on the "volume_id" field.
func VolumeIDLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldVolumeID, v))
}

// VolumeIDContains applies the Contains predicate on the "volume_id" field.
func VolumeIDContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldVolumeID, v))
}

// VolumeIDHasPrefix applies the HasPrefix predicate on the "volume_id" field.
func VolumeIDHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldVolumeID, v))
}

// VolumeIDHasSuffix applies the HasSuffix predicate on the "volume_id" field.
func VolumeIDHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldVolumeID, v))
}

// VolumeIDIsNil applies the IsNil predicate on the "volume_id" field.
func VolumeIDIsNil() predicate.Instance {
	return predicate.Instance(sql.FieldIsNull(FieldVolumeID))
}

// VolumeIDNotNil applies the NotNil predicate on the "volume_id" field.
func VolumeIDNotNil() predicate.Instance {
	return predicate.Instance(sql.FieldNotNull(FieldVolumeID))
}

// VolumeIDEqualFold applies the EqualFold predicate on the "volume_id" field.
func VolumeIDEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldVolumeID, v))
}

// VolumeIDContainsFold applies the ContainsFold predicate on the "volume_id" field.
func VolumeIDContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldVolumeID, v))
}

// NetbirdConfigEQ applies the EQ predicate on the "netbird_config" field.
func NetbirdConfigEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldNetbirdConfig, v))
}

// NetbirdConfigNEQ applies the NEQ predicate on the "netbird_config" field.
func NetbirdConfigNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldNetbirdConfig, v))
}

// NetbirdConfigIn applies the In predicate on the "netbird_config" field.
func NetbirdConfigIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldNetbirdConfig, vs...))
}

// NetbirdConfigNotIn applies the NotIn predicate on the "netbird_config" field.
func NetbirdConfigNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldNetbirdConfig, vs...))
}

// NetbirdConfigGT applies the GT predicate on the "netbird_config" field.
func NetbirdConfigGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldNetbirdConfig, v))
}

// NetbirdConfigGTE applies the GTE predicate on the "netbird_config" field.
func NetbirdConfigGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldNetbirdConfig, v))
}

// NetbirdConfigLT applies the LT predicate on the "netbird_config" field.
func NetbirdConfigLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldNetbirdConfig, v))
}

// NetbirdConfigLTE applies the LTE predicate on the "netbird_config" field.
func NetbirdConfigLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldNetbirdConfig, v))
}

// NetbirdConfigContains applies the Contains predicate on the "netbird_config" field.
func NetbirdConfigContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldNetbirdConfig, v))
}

// NetbirdConfigHasPrefix applies the HasPrefix predicate on the "netbird_config" field.
func NetbirdConfigHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldNetbirdConfig, v))
}

// NetbirdConfigHasSuffix applies the HasSuffix predicate on the "netbird_config" field.
func NetbirdConfigHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldNetbirdConfig, v))
}

// NetbirdConfigIsNil applies the IsNil predicate on the "netbird_config" field.
func NetbirdConfigIsNil() predicate.Instance {
	return predicate.Instance(sql.FieldIsNull(FieldNetbirdConfig))
}

// NetbirdConfigNotNil applies the NotNil predicate on the "netbird_config" field.
func NetbirdConfigNotNil() predicate.Instance {
	return predicate.Instance(sql.FieldNotNull(FieldNetbirdConfig))
}

// NetbirdConfigEqualFold applies the EqualFold predicate on the "netbird_config" field.
func NetbirdConfigEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldNetbirdConfig, v))
}

// NetbirdConfigContainsFold applies the ContainsFold predicate on the "netbird_config" field.
func NetbirdConfigContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldNetbirdConfig, v))
}

// AgentSecretEQ applies the EQ predicate on the "agent_secret" field.
func AgentSecretEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldAgentSecret, v))
}

// AgentSecretNEQ applies the NEQ predicate on the "agent_secret" field.
func AgentSecretNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldAgentSecret, v))
}

// AgentSecretIn applies the In predicate on the "agent_secret" field.
func AgentSecretIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldAgentSecret, vs...))
}

// AgentSecretNotIn applies the NotIn predicate on the "agent_secret" field.
func AgentSecretNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldAgentSecret, vs...))
}

// AgentSecretGT applies the GT predicate on the "agent_secret" field.
func AgentSecretGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldAgentSecret, v))
}

// AgentSecretGTE applies the GTE predicate on the "agent_secret" field.
func AgentSecretGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldAgentSecret, v))
}

// AgentSecretLT applies the LT predicate on the "agent_secret" field.
func AgentSecretLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldAgentSecret, v))
}

// AgentSecretLTE applies the LTE predicate on the "agent_secret" field.
func AgentSecretLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldAgentSecret, v))
}

// AgentSecretContains applies the Contains predicate on the "agent_secret" field.
func AgentSecretContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldAgentSecret, v))
}

// AgentSecretHasPrefix applies the HasPrefix predicate on the "agent_secret" field.
func AgentSecretHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldAgentSecret, v))
}

// AgentSecretHasSuffix applies the HasSuffix predicate on the "agent_secret" field.
func AgentSecretHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldAgentSecret, v))
}

// AgentSecretIsNil applies the IsNil predicate on the "agent_secret" field.
func AgentSecretIsNil() predicate.Instance {
	return predicate.Instance(sql.FieldIsNull(FieldAgentSecret))
}

// AgentSecretNotNil applies the NotNil predicate on the "agent_secret" field.
func AgentSecretNotNil() predicate.Instance {
	return predicate.Instance(sql.FieldNotNull(FieldAgentSecret))
}

// AgentSecretEqualFold applies the EqualFold predicate on the "agent_secret" field.
func AgentSecretEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldAgentSecret, v))
}

// AgentSecretContainsFold applies the ContainsFold predicate on the "agent_secret" field.
func AgentSecretContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldAgentSecret, v))
}

// LastActivityAtEQ applies the EQ predicate on the "last_activity_at" field.
func LastActivityAtEQ(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldLastActivityAt, v))
}

// LastActivityAtNEQ applies the NEQ predicate on the "last_activity_at" field.
func LastActivityAtNEQ(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldLastActivityAt, v))
}

// LastActivityAtIn applies the In predicate on the "last_activity_at" field.
func LastActivityAtIn(vs ...time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldLastActivityAt, vs...))
}

// LastActivityAtNotIn applies the NotIn predicate on the "last_activity_at" field.
func LastActivityAtNotIn(vs ...time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldLastActivityAt, vs...))
}

// LastActivityAtGT applies the GT predicate on the "last_activity_at" field.
func LastActivityAtGT(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldLastActivityAt, v))
}

// LastActivityAtGTE applies the GTE predicate on the "last_activity_at" field.
func LastActivityAtGTE(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldLastActivityAt, v))
}

// LastActivityAtLT applies the LT predicate on the "last_activity_at" field.
func LastActivityAtLT(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldLastActivityAt, v))
}

// LastActivityAtLTE applies the LTE predicate on the "last_activity_at" field.
func LastActivityAtLTE(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldLastActivityAt, v))
}

// LastActivityAtIsNil applies the IsNil predicate on the "last_activity_at" field.
func LastActivityAtIsNil() predicate.Instance {
	return predicate.Instance(sql.FieldIsNull(FieldLastActivityAt))
}

// LastActivityAtNotNil applies the NotNil predicate on the "last_activity_at" field.
func LastActivityAtNotNil() predicate.Instance {
	return predicate.Instance(sql.FieldNotNull(FieldLastActivityAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Instance {
	return predicate.Instance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Instance {
	return predicate.Instance(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Instance) predicate.Instance {
	return predicate.Instance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Instance) predicate.Instance {
	return predicate.Instance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Instance) predicate.Instance {
	return predicate.Instance(sql.NotPredicates(p))
}
