// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// InstancesColumns holds the columns for the "instances" table.
	InstancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "provider", Type: field.TypeString},
		{Name: "provider_id", Type: field.TypeString},
		{Name: "host", Type: field.TypeString, Nullable: true},
		{Name: "port", Type: field.TypeInt, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "provisioning"},
		{Name: "volume_id", Type: field.TypeString, Nullable: true},
		{Name: "netbird_config", Type: field.TypeString, Nullable: true},
		{Name: "agent_secret", Type: field.TypeString, Nullable: true},
		{Name: "last_activity_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_instances", Type: field.TypeInt},
	}
	// InstancesTable holds the schema information for the "instances" table.
	InstancesTable = &schema.Table{
		Name:       "instances",
		Columns:    InstancesColumns,
		PrimaryKey: []*schema.Column{InstancesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "instances_users_instances",
				Columns:    []*schema.Column{InstancesColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "api_key", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "name", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "stripe_customer_id", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "stripe_subscription_id", Type: field.TypeString, Nullable: true},
		{Name: "subscription_status", Type: field.TypeString, Default: "inactive"},
		{Name: "plan", Type: field.TypeString, Default: "free"},
		{Name: "usage_hours", Type: field.TypeFloat64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		InstancesTable,
		UsersTable,
	}
)

func init() {
	InstancesTable.ForeignKeys[0].RefTable = UsersTable
}
