// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/logan/cloudcode/internal/ent/chatmessage"
	"github.com/logan/cloudcode/internal/ent/conversation"
	"github.com/logan/cloudcode/internal/ent/predicate"
)

// ChatMessageQuery is the builder for querying ChatMessage entities.
type ChatMessageQuery struct {
	config
	ctx              *QueryContext
	order            []chatmessage.OrderOption
	inters           []Interceptor
	predicates       []predicate.ChatMessage
	withConversation *ConversationQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChatMessageQuery builder.
func (_q *ChatMessageQuery) Where(ps ...predicate.ChatMessage) *ChatMessageQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChatMessageQuery) Limit(limit int) *ChatMessageQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChatMessageQuery) Offset(offset int) *ChatMessageQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChatMessageQuery) Unique(unique bool) *ChatMessageQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChatMessageQuery) Order(o ...chatmessage.OrderOption) *ChatMessageQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryConversation chains the current query on the "conversation" edge.
func (_q *ChatMessageQuery) QueryConversation() *ConversationQuery {
	query := (&ConversationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chatmessage.Table, chatmessage.FieldID, selector),
			sqlgraph.To(conversation.Table, conversation.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, chatmessage.ConversationTable, chatmessage.ConversationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChatMessage entity from the query.
// Returns a *NotFoundError when no ChatMessage was found.
func (_q *ChatMessageQuery) First(ctx context.Context) (*ChatMessage, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chatmessage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChatMessageQuery) FirstX(ctx context.Context) *ChatMessage {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChatMessage ID from the query.
// Returns a *NotFoundError when no ChatMessage ID was found.
func (_q *ChatMessageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chatmessage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChatMessageQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChatMessage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChatMessage entity is found.
// Returns a *NotFoundError when no ChatMessage entities are found.
func (_q *ChatMessageQuery) Only(ctx context.Context) (*ChatMessage, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chatmessage.Label}
	default:
		return nil, &NotSingularError{chatmessage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChatMessageQuery) OnlyX(ctx context.Context) *ChatMessage {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChatMessage ID in the query.
// Returns a *NotSingularError when more than one ChatMessage ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChatMessageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chatmessage.Label}
	default:
		err = &NotSingularError{chatmessage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChatMessageQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChatMessages.
func (_q *ChatMessageQuery) All(ctx context.Context) ([]*ChatMessage, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChatMessage, *ChatMessageQuery]()
	return withInterceptors[[]*ChatMessage](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChatMessageQuery) AllX(ctx context.Context) []*ChatMessage {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChatMessage IDs.
func (_q *ChatMessageQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(chatmessage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChatMessageQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChatMessageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChatMessageQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChatMessageQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChatMessageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChatMessageQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChatMessageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChatMessageQuery) Clone() *ChatMessageQuery {
	if _q == nil {
		return nil
	}
	return &ChatMessageQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]chatmessage.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.ChatMessage{}, _q.predicates...),
		withConversation: _q.withConversation.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithConversation tells the query-builder to eager-load the nodes that are connected to
// the "conversation" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChatMessageQuery) WithConversation(opts ...func(*ConversationQuery)) *ChatMessageQuery {
	query := (&ConversationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withConversation = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Role chatmessage.Role `json:"role,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChatMessage.Query().
//		GroupBy(chatmessage.FieldRole).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChatMessageQuery) GroupBy(field string, fields ...string) *ChatMessageGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChatMessageGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = chatmessage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Role chatmessage.Role `json:"role,omitempty"`
//	}
//
//	client.ChatMessage.Query().
//		Select(chatmessage.FieldRole).
//		Scan(ctx, &v)
func (_q *ChatMessageQuery) Select(fields ...string) *ChatMessageSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChatMessageSelect{ChatMessageQuery: _q}
	sbuild.label = chatmessage.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChatMessageSelect configured with the given aggregations.
func (_q *ChatMessageQuery) Aggregate(fns ...AggregateFunc) *ChatMessageSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChatMessageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !chatmessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChatMessageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChatMessage, error) {
	var (
		nodes       = []*ChatMessage{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withConversation != nil,
		}
	)
	if _q.withConversation != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, chatmessage.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChatMessage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChatMessage{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withConversation; query != nil {
		if err := _q.loadConversation(ctx, query, nodes, nil,
			func(n *ChatMessage, e *Conversation) { n.Edges.Conversation = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChatMessageQuery) loadConversation(ctx context.Context, query *ConversationQuery, nodes []*ChatMessage, init func(*ChatMessage), assign func(*ChatMessage, *Conversation)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ChatMessage)
	for i := range nodes {
		if nodes[i].conversation_messages == nil {
			continue
		}
		fk := *nodes[i].conversation_messages
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(conversation.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "conversation_messages" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ChatMessageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChatMessageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chatmessage.Table, chatmessage.Columns, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatmessage.FieldID)
		for i := range fields {
			if fields[i] != chatmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChatMessageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(chatmessage.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = chatmessage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChatMessageGroupBy is the group-by builder for ChatMessage entities.
type ChatMessageGroupBy struct {
	selector
	build *ChatMessageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChatMessageGroupBy) Aggregate(fns ...AggregateFunc) *ChatMessageGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChatMessageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatMessageQuery, *ChatMessageGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChatMessageGroupBy) sqlScan(ctx context.Context, root *ChatMessageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChatMessageSelect is the builder for selecting fields of ChatMessage entities.
type ChatMessageSelect struct {
	*ChatMessageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChatMessageSelect) Aggregate(fns ...AggregateFunc) *ChatMessageSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChatMessageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatMessageQuery, *ChatMessageSelect](ctx, _s.ChatMessageQuery, _s, _s.inters, v)
}

func (_s *ChatMessageSelect) sqlScan(ctx context.Context, root *ChatMessageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
