// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/logan/cloudcode/internal/ent/instance"
	"github.com/logan/cloudcode/internal/ent/user"
)

// InstanceCreate is the builder for creating a Instance entity.
type InstanceCreate struct {
	config
	mutation *InstanceMutation
	hooks    []Hook
}

// SetProvider sets the "provider" field.
func (_c *InstanceCreate) SetProvider(v string) *InstanceCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *InstanceCreate) SetProviderID(v string) *InstanceCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetHost sets the "host" field.
func (_c *InstanceCreate) SetHost(v string) *InstanceCreate {
	_c.mutation.SetHost(v)
	return _c
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_c *InstanceCreate) SetNillableHost(v *string) *InstanceCreate {
	if v != nil {
		_c.SetHost(*v)
	}
	return _c
}

// SetPort sets the "port" field.
func (_c *InstanceCreate) SetPort(v int) *InstanceCreate {
	_c.mutation.SetPort(v)
	return _c
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_c *InstanceCreate) SetNillablePort(v *int) *InstanceCreate {
	if v != nil {
		_c.SetPort(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *InstanceCreate) SetStatus(v string) *InstanceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InstanceCreate) SetNillableStatus(v *string) *InstanceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetVolumeID sets the "volume_id" field.
func (_c *InstanceCreate) SetVolumeID(v string) *InstanceCreate {
	_c.mutation.SetVolumeID(v)
	return _c
}

// SetNillableVolumeID sets the "volume_id" field if the given value is not nil.
func (_c *InstanceCreate) SetNillableVolumeID(v *string) *InstanceCreate {
	if v != nil {
		_c.SetVolumeID(*v)
	}
	return _c
}

// SetNetbirdConfig sets the "netbird_config" field.
func (_c *InstanceCreate) SetNetbirdConfig(v string) *InstanceCreate {
	_c.mutation.SetNetbirdConfig(v)
	return _c
}

// SetNillableNetbirdConfig sets the "netbird_config" field if the given value is not nil.
func (_c *InstanceCreate) SetNillableNetbirdConfig(v *string) *InstanceCreate {
	if v != nil {
		_c.SetNetbirdConfig(*v)
	}
	return _c
}

// SetAgentSecret sets the "agent_secret" field.
func (_c *InstanceCreate) SetAgentSecret(v string) *InstanceCreate {
	_c.mutation.SetAgentSecret(v)
	return _c
}

// SetNillableAgentSecret sets the "agent_secret" field if the given value is not nil.
func (_c *InstanceCreate) SetNillableAgentSecret(v *string) *InstanceCreate {
	if v != nil {
		_c.SetAgentSecret(*v)
	}
	return _c
}

// SetLastActivityAt sets the "last_activity_at" field.
func (_c *InstanceCreate) SetLastActivityAt(v time.Time) *InstanceCreate {
	_c.mutation.SetLastActivityAt(v)
	return _c
}

// SetNillableLastActivityAt sets the "last_activity_at" field if the given value is not nil.
func (_c *InstanceCreate) SetNillableLastActivityAt(v *time.Time) *InstanceCreate {
	if v != nil {
		_c.SetLastActivityAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InstanceCreate) SetCreatedAt(v time.Time) *InstanceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InstanceCreate) SetNillableCreatedAt(v *time.Time) *InstanceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InstanceCreate) SetUpdatedAt(v time.Time) *InstanceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InstanceCreate) SetNillableUpdatedAt(v *time.Time) *InstanceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *InstanceCreate) SetOwnerID(id int) *InstanceCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *InstanceCreate) SetOwner(v *User) *InstanceCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the InstanceMutation object of the builder.
func (_c *InstanceCreate) Mutation() *InstanceMutation {
	return _c.mutation
}

// Save creates the Instance in the database.
func (_c *InstanceCreate) Save(ctx context.Context) (*Instance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InstanceCreate) SaveX(ctx context.Context) *Instance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InstanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InstanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InstanceCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := instance.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := instance.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := instance.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InstanceCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "Instance.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := instance.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Instance.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "Instance.provider_id"`)}
	}
	if v, ok := _c.mutation.ProviderID(); ok {
		if err := instance.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "Instance.provider_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Instance.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Instance.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Instance.updated_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Instance.owner"`)}
	}
	return nil
}

func (_c *InstanceCreate) sqlSave(ctx context.Context) (*Instance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InstanceCreate) createSpec() (*Instance, *sqlgraph.CreateSpec) {
	var (
		_node = &Instance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(instance.Table, sqlgraph.NewFieldSpec(instance.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(instance.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ProviderID(); ok {
		_spec.SetField(instance.FieldProviderID, field.TypeString, value)
		_node.ProviderID = value
	}
	if value, ok := _c.mutation.Host(); ok {
		_spec.SetField(instance.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := _c.mutation.Port(); ok {
		_spec.SetField(instance.FieldPort, field.TypeInt, value)
		_node.Port = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(instance.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.VolumeID(); ok {
		_spec.SetField(instance.FieldVolumeID, field.TypeString, value)
		_node.VolumeID = value
	}
	if value, ok := _c.mutation.NetbirdConfig(); ok {
		_spec.SetField(instance.FieldNetbirdConfig, field.TypeString, value)
		_node.NetbirdConfig = value
	}
	if value, ok := _c.mutation.AgentSecret(); ok {
		_spec.SetField(instance.FieldAgentSecret, field.TypeString, value)
		_node.AgentSecret = value
	}
	if value, ok := _c.mutation.LastActivityAt(); ok {
		_spec.SetField(instance.FieldLastActivityAt, field.TypeTime, value)
		_node.LastActivityAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(instance.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(instance.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   instance.OwnerTable,
			Columns: []string{instance.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_instances = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InstanceCreateBulk is the builder for creating many Instance entities in bulk.
type InstanceCreateBulk struct {
	config
	err      error
	builders []*InstanceCreate
}

// Save creates the Instance entities in the database.
func (_c *InstanceCreateBulk) Save(ctx context.Context) ([]*Instance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Instance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InstanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InstanceCreateBulk) SaveX(ctx context.Context) []*Instance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InstanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InstanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
