// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/logan/cloudcode/internal/ent/instance"
	"github.com/logan/cloudcode/internal/ent/predicate"
	"github.com/logan/cloudcode/internal/ent/user"
)

// InstanceUpdate is the builder for updating Instance entities.
type InstanceUpdate struct {
	config
	hooks    []Hook
	mutation *InstanceMutation
}

// Where appends a list predicates to the InstanceUpdate builder.
func (_u *InstanceUpdate) Where(ps ...predicate.Instance) *InstanceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *InstanceUpdate) SetProvider(v string) *InstanceUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableProvider(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *InstanceUpdate) SetProviderID(v string) *InstanceUpdate {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableProviderID(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *InstanceUpdate) SetHost(v string) *InstanceUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableHost(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// ClearHost clears the value of the "host" field.
func (_u *InstanceUpdate) ClearHost() *InstanceUpdate {
	_u.mutation.ClearHost()
	return _u
}

// SetPort sets the "port" field.
func (_u *InstanceUpdate) SetPort(v int) *InstanceUpdate {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillablePort(v *int) *InstanceUpdate {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *InstanceUpdate) AddPort(v int) *InstanceUpdate {
	_u.mutation.AddPort(v)
	return _u
}

// ClearPort clears the value of the "port" field.
func (_u *InstanceUpdate) ClearPort() *InstanceUpdate {
	_u.mutation.ClearPort()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InstanceUpdate) SetStatus(v string) *InstanceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableStatus(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVolumeID sets the "volume_id" field.
func (_u *InstanceUpdate) SetVolumeID(v string) *InstanceUpdate {
	_u.mutation.SetVolumeID(v)
	return _u
}

// SetNillableVolumeID sets the "volume_id" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableVolumeID(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetVolumeID(*v)
	}
	return _u
}

// ClearVolumeID clears the value of the "volume_id" field.
func (_u *InstanceUpdate) ClearVolumeID() *InstanceUpdate {
	_u.mutation.ClearVolumeID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InstanceUpdate) SetUpdatedAt(v time.Time) *InstanceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *InstanceUpdate) SetOwnerID(id int) *InstanceUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *InstanceUpdate) SetOwner(v *User) *InstanceUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the InstanceMutation object of the builder.
func (_u *InstanceUpdate) Mutation() *InstanceMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *InstanceUpdate) ClearOwner() *InstanceUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InstanceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstanceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InstanceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstanceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InstanceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := instance.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InstanceUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := instance.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Instance.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderID(); ok {
		if err := instance.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "Instance.provider_id": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Instance.owner"`)
	}
	return nil
}

func (_u *InstanceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(instance.Table, instance.Columns, sqlgraph.NewFieldSpec(instance.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(instance.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(instance.FieldProviderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(instance.FieldHost, field.TypeString, value)
	}
	if _u.mutation.HostCleared() {
		_spec.ClearField(instance.FieldHost, field.TypeString)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(instance.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(instance.FieldPort, field.TypeInt, value)
	}
	if _u.mutation.PortCleared() {
		_spec.ClearField(instance.FieldPort, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(instance.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.VolumeID(); ok {
		_spec.SetField(instance.FieldVolumeID, field.TypeString, value)
	}
	if _u.mutation.VolumeIDCleared() {
		_spec.ClearField(instance.FieldVolumeID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(instance.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   instance.OwnerTable,
			Columns: []string{instance.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   instance.OwnerTable,
			Columns: []string{instance.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{instance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InstanceUpdateOne is the builder for updating a single Instance entity.
type InstanceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InstanceMutation
}

// SetProvider sets the "provider" field.
func (_u *InstanceUpdateOne) SetProvider(v string) *InstanceUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableProvider(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *InstanceUpdateOne) SetProviderID(v string) *InstanceUpdateOne {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableProviderID(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *InstanceUpdateOne) SetHost(v string) *InstanceUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableHost(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// ClearHost clears the value of the "host" field.
func (_u *InstanceUpdateOne) ClearHost() *InstanceUpdateOne {
	_u.mutation.ClearHost()
	return _u
}

// SetPort sets the "port" field.
func (_u *InstanceUpdateOne) SetPort(v int) *InstanceUpdateOne {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillablePort(v *int) *InstanceUpdateOne {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *InstanceUpdateOne) AddPort(v int) *InstanceUpdateOne {
	_u.mutation.AddPort(v)
	return _u
}

// ClearPort clears the value of the "port" field.
func (_u *InstanceUpdateOne) ClearPort() *InstanceUpdateOne {
	_u.mutation.ClearPort()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InstanceUpdateOne) SetStatus(v string) *InstanceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableStatus(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVolumeID sets the "volume_id" field.
func (_u *InstanceUpdateOne) SetVolumeID(v string) *InstanceUpdateOne {
	_u.mutation.SetVolumeID(v)
	return _u
}

// SetNillableVolumeID sets the "volume_id" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableVolumeID(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetVolumeID(*v)
	}
	return _u
}

// ClearVolumeID clears the value of the "volume_id" field.
func (_u *InstanceUpdateOne) ClearVolumeID() *InstanceUpdateOne {
	_u.mutation.ClearVolumeID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InstanceUpdateOne) SetUpdatedAt(v time.Time) *InstanceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *InstanceUpdateOne) SetOwnerID(id int) *InstanceUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *InstanceUpdateOne) SetOwner(v *User) *InstanceUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the InstanceMutation object of the builder.
func (_u *InstanceUpdateOne) Mutation() *InstanceMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *InstanceUpdateOne) ClearOwner() *InstanceUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the InstanceUpdate builder.
func (_u *InstanceUpdateOne) Where(ps ...predicate.Instance) *InstanceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InstanceUpdateOne) Select(field string, fields ...string) *InstanceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Instance entity.
func (_u *InstanceUpdateOne) Save(ctx context.Context) (*Instance, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstanceUpdateOne) SaveX(ctx context.Context) *Instance {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InstanceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstanceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InstanceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := instance.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InstanceUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := instance.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Instance.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderID(); ok {
		if err := instance.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "Instance.provider_id": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Instance.owner"`)
	}
	return nil
}

func (_u *InstanceUpdateOne) sqlSave(ctx context.Context) (_node *Instance, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(instance.Table, instance.Columns, sqlgraph.NewFieldSpec(instance.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Instance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, instance.FieldID)
		for _, f := range fields {
			if !instance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != instance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(instance.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(instance.FieldProviderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(instance.FieldHost, field.TypeString, value)
	}
	if _u.mutation.HostCleared() {
		_spec.ClearField(instance.FieldHost, field.TypeString)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(instance.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(instance.FieldPort, field.TypeInt, value)
	}
	if _u.mutation.PortCleared() {
		_spec.ClearField(instance.FieldPort, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(instance.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.VolumeID(); ok {
		_spec.SetField(instance.FieldVolumeID, field.TypeString, value)
	}
	if _u.mutation.VolumeIDCleared() {
		_spec.ClearField(instance.FieldVolumeID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(instance.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   instance.OwnerTable,
			Columns: []string{instance.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   instance.OwnerTable,
			Columns: []string{instance.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Instance{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{instance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
