// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/logan/cloudcode/internal/ent/chatmessage"
	"github.com/logan/cloudcode/internal/ent/conversation"
	"github.com/logan/cloudcode/internal/ent/instance"
	"github.com/logan/cloudcode/internal/ent/schema"
	"github.com/logan/cloudcode/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chatmessageFields := schema.ChatMessage{}.Fields()
	_ = chatmessageFields
	// chatmessageDescContent is the schema descriptor for content field.
	chatmessageDescContent := chatmessageFields[1].Descriptor()
	// chatmessage.DefaultContent holds the default value on creation for the content field.
	chatmessage.DefaultContent = chatmessageDescContent.Default.(string)
	// chatmessageDescCreatedAt is the schema descriptor for created_at field.
	chatmessageDescCreatedAt := chatmessageFields[3].Descriptor()
	// chatmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	chatmessage.DefaultCreatedAt = chatmessageDescCreatedAt.Default.(func() time.Time)
	conversationFields := schema.Conversation{}.Fields()
	_ = conversationFields
	// conversationDescProjectPath is the schema descriptor for project_path field.
	conversationDescProjectPath := conversationFields[0].Descriptor()
	// conversation.DefaultProjectPath holds the default value on creation for the project_path field.
	conversation.DefaultProjectPath = conversationDescProjectPath.Default.(string)
	// conversationDescTitle is the schema descriptor for title field.
	conversationDescTitle := conversationFields[1].Descriptor()
	// conversation.DefaultTitle holds the default value on creation for the title field.
	conversation.DefaultTitle = conversationDescTitle.Default.(string)
	// conversationDescCreatedAt is the schema descriptor for created_at field.
	conversationDescCreatedAt := conversationFields[2].Descriptor()
	// conversation.DefaultCreatedAt holds the default value on creation for the created_at field.
	conversation.DefaultCreatedAt = conversationDescCreatedAt.Default.(func() time.Time)
	// conversationDescUpdatedAt is the schema descriptor for updated_at field.
	conversationDescUpdatedAt := conversationFields[3].Descriptor()
	// conversation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	conversation.DefaultUpdatedAt = conversationDescUpdatedAt.Default.(func() time.Time)
	// conversation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	conversation.UpdateDefaultUpdatedAt = conversationDescUpdatedAt.UpdateDefault.(func() time.Time)
	instanceFields := schema.Instance{}.Fields()
	_ = instanceFields
	// instanceDescProvider is the schema descriptor for provider field.
	instanceDescProvider := instanceFields[0].Descriptor()
	// instance.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	instance.ProviderValidator = instanceDescProvider.Validators[0].(func(string) error)
	// instanceDescProviderID is the schema descriptor for provider_id field.
	instanceDescProviderID := instanceFields[1].Descriptor()
	// instance.ProviderIDValidator is a validator for the "provider_id" field. It is called by the builders before save.
	instance.ProviderIDValidator = instanceDescProviderID.Validators[0].(func(string) error)
	// instanceDescStatus is the schema descriptor for status field.
	instanceDescStatus := instanceFields[4].Descriptor()
	// instance.DefaultStatus holds the default value on creation for the status field.
	instance.DefaultStatus = instanceDescStatus.Default.(string)
	// instanceDescCreatedAt is the schema descriptor for created_at field.
	instanceDescCreatedAt := instanceFields[9].Descriptor()
	// instance.DefaultCreatedAt holds the default value on creation for the created_at field.
	instance.DefaultCreatedAt = instanceDescCreatedAt.Default.(func() time.Time)
	// instanceDescUpdatedAt is the schema descriptor for updated_at field.
	instanceDescUpdatedAt := instanceFields[10].Descriptor()
	// instance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	instance.DefaultUpdatedAt = instanceDescUpdatedAt.Default.(func() time.Time)
	// instance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	instance.UpdateDefaultUpdatedAt = instanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[2].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescSubscriptionStatus is the schema descriptor for subscription_status field.
	userDescSubscriptionStatus := userFields[5].Descriptor()
	// user.DefaultSubscriptionStatus holds the default value on creation for the subscription_status field.
	user.DefaultSubscriptionStatus = userDescSubscriptionStatus.Default.(string)
	// userDescPlan is the schema descriptor for plan field.
	userDescPlan := userFields[6].Descriptor()
	// user.DefaultPlan holds the default value on creation for the plan field.
	user.DefaultPlan = userDescPlan.Default.(string)
	// userDescUsageHours is the schema descriptor for usage_hours field.
	userDescUsageHours := userFields[7].Descriptor()
	// user.DefaultUsageHours holds the default value on creation for the usage_hours field.
	user.DefaultUsageHours = userDescUsageHours.Default.(float64)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[10].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[11].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
