// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/logan/cloudcode/internal/ent/instance"
	"github.com/logan/cloudcode/internal/ent/schema"
	"github.com/logan/cloudcode/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	instanceFields := schema.Instance{}.Fields()
	_ = instanceFields
	// instanceDescProvider is the schema descriptor for provider field.
	instanceDescProvider := instanceFields[0].Descriptor()
	// instance.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	instance.ProviderValidator = instanceDescProvider.Validators[0].(func(string) error)
	// instanceDescProviderID is the schema descriptor for provider_id field.
	instanceDescProviderID := instanceFields[1].Descriptor()
	// instance.ProviderIDValidator is a validator for the "provider_id" field. It is called by the builders before save.
	instance.ProviderIDValidator = instanceDescProviderID.Validators[0].(func(string) error)
	// instanceDescStatus is the schema descriptor for status field.
	instanceDescStatus := instanceFields[4].Descriptor()
	// instance.DefaultStatus holds the default value on creation for the status field.
	instance.DefaultStatus = instanceDescStatus.Default.(string)
	// instanceDescCreatedAt is the schema descriptor for created_at field.
	instanceDescCreatedAt := instanceFields[8].Descriptor()
	// instance.DefaultCreatedAt holds the default value on creation for the created_at field.
	instance.DefaultCreatedAt = instanceDescCreatedAt.Default.(func() time.Time)
	// instanceDescUpdatedAt is the schema descriptor for updated_at field.
	instanceDescUpdatedAt := instanceFields[9].Descriptor()
	// instance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	instance.DefaultUpdatedAt = instanceDescUpdatedAt.Default.(func() time.Time)
	// instance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	instance.UpdateDefaultUpdatedAt = instanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescAPIKey is the schema descriptor for api_key field.
	userDescAPIKey := userFields[1].Descriptor()
	// user.APIKeyValidator is a validator for the "api_key" field. It is called by the builders before save.
	user.APIKeyValidator = userDescAPIKey.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[2].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[3].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
