// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/logan/cloudcode/internal/ent/conversation"
	"github.com/logan/cloudcode/internal/ent/instance"
	"github.com/logan/cloudcode/internal/ent/user"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetEmail sets the "email" field.
func (_c *UserCreate) SetEmail(v string) *UserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetAPIKey sets the "api_key" field.
func (_c *UserCreate) SetAPIKey(v string) *UserCreate {
	_c.mutation.SetAPIKey(v)
	return _c
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_c *UserCreate) SetNillableAPIKey(v *string) *UserCreate {
	if v != nil {
		_c.SetAPIKey(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UserCreate) SetName(v string) *UserCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *UserCreate) SetNillableName(v *string) *UserCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (_c *UserCreate) SetStripeCustomerID(v string) *UserCreate {
	_c.mutation.SetStripeCustomerID(v)
	return _c
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (_c *UserCreate) SetNillableStripeCustomerID(v *string) *UserCreate {
	if v != nil {
		_c.SetStripeCustomerID(*v)
	}
	return _c
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (_c *UserCreate) SetStripeSubscriptionID(v string) *UserCreate {
	_c.mutation.SetStripeSubscriptionID(v)
	return _c
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (_c *UserCreate) SetNillableStripeSubscriptionID(v *string) *UserCreate {
	if v != nil {
		_c.SetStripeSubscriptionID(*v)
	}
	return _c
}

// SetSubscriptionStatus sets the "subscription_status" field.
func (_c *UserCreate) SetSubscriptionStatus(v string) *UserCreate {
	_c.mutation.SetSubscriptionStatus(v)
	return _c
}

// SetNillableSubscriptionStatus sets the "subscription_status" field if the given value is not nil.
func (_c *UserCreate) SetNillableSubscriptionStatus(v *string) *UserCreate {
	if v != nil {
		_c.SetSubscriptionStatus(*v)
	}
	return _c
}

// SetPlan sets the "plan" field.
func (_c *UserCreate) SetPlan(v string) *UserCreate {
	_c.mutation.SetPlan(v)
	return _c
}

// SetNillablePlan sets the "plan" field if the given value is not nil.
func (_c *UserCreate) SetNillablePlan(v *string) *UserCreate {
	if v != nil {
		_c.SetPlan(*v)
	}
	return _c
}

// SetUsageHours sets the "usage_hours" field.
func (_c *UserCreate) SetUsageHours(v float64) *UserCreate {
	_c.mutation.SetUsageHours(v)
	return _c
}

// SetNillableUsageHours sets the "usage_hours" field if the given value is not nil.
func (_c *UserCreate) SetNillableUsageHours(v *float64) *UserCreate {
	if v != nil {
		_c.SetUsageHours(*v)
	}
	return _c
}

// SetAnthropicAPIKey sets the "anthropic_api_key" field.
func (_c *UserCreate) SetAnthropicAPIKey(v string) *UserCreate {
	_c.mutation.SetAnthropicAPIKey(v)
	return _c
}

// SetNillableAnthropicAPIKey sets the "anthropic_api_key" field if the given value is not nil.
func (_c *UserCreate) SetNillableAnthropicAPIKey(v *string) *UserCreate {
	if v != nil {
		_c.SetAnthropicAPIKey(*v)
	}
	return _c
}

// SetClaudeOauthToken sets the "claude_oauth_token" field.
func (_c *UserCreate) SetClaudeOauthToken(v string) *UserCreate {
	_c.mutation.SetClaudeOauthToken(v)
	return _c
}

// SetNillableClaudeOauthToken sets the "claude_oauth_token" field if the given value is not nil.
func (_c *UserCreate) SetNillableClaudeOauthToken(v *string) *UserCreate {
	if v != nil {
		_c.SetClaudeOauthToken(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserCreate) SetUpdatedAt(v time.Time) *UserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableUpdatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddInstanceIDs adds the "instances" edge to the Instance entity by IDs.
func (_c *UserCreate) AddInstanceIDs(ids ...int) *UserCreate {
	_c.mutation.AddInstanceIDs(ids...)
	return _c
}

// AddInstances adds the "instances" edges to the Instance entity.
func (_c *UserCreate) AddInstances(v ...*Instance) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInstanceIDs(ids...)
}

// AddConversationIDs adds the "conversations" edge to the Conversation entity by IDs.
func (_c *UserCreate) AddConversationIDs(ids ...int) *UserCreate {
	_c.mutation.AddConversationIDs(ids...)
	return _c
}

// AddConversations adds the "conversations" edges to the Conversation entity.
func (_c *UserCreate) AddConversations(v ...*Conversation) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddConversationIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := user.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.SubscriptionStatus(); !ok {
		v := user.DefaultSubscriptionStatus
		_c.mutation.SetSubscriptionStatus(v)
	}
	if _, ok := _c.mutation.Plan(); !ok {
		v := user.DefaultPlan
		_c.mutation.SetPlan(v)
	}
	if _, ok := _c.mutation.UsageHours(); !ok {
		v := user.DefaultUsageHours
		_c.mutation.SetUsageHours(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := user.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "User.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubscriptionStatus(); !ok {
		return &ValidationError{Name: "subscription_status", err: errors.New(`ent: missing required field "User.subscription_status"`)}
	}
	if _, ok := _c.mutation.Plan(); !ok {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required field "User.plan"`)}
	}
	if _, ok := _c.mutation.UsageHours(); !ok {
		return &ValidationError{Name: "usage_hours", err: errors.New(`ent: missing required field "User.usage_hours"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "User.updated_at"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.APIKey(); ok {
		_spec.SetField(user.FieldAPIKey, field.TypeString, value)
		_node.APIKey = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.StripeCustomerID(); ok {
		_spec.SetField(user.FieldStripeCustomerID, field.TypeString, value)
		_node.StripeCustomerID = &value
	}
	if value, ok := _c.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(user.FieldStripeSubscriptionID, field.TypeString, value)
		_node.StripeSubscriptionID = &value
	}
	if value, ok := _c.mutation.SubscriptionStatus(); ok {
		_spec.SetField(user.FieldSubscriptionStatus, field.TypeString, value)
		_node.SubscriptionStatus = value
	}
	if value, ok := _c.mutation.Plan(); ok {
		_spec.SetField(user.FieldPlan, field.TypeString, value)
		_node.Plan = value
	}
	if value, ok := _c.mutation.UsageHours(); ok {
		_spec.SetField(user.FieldUsageHours, field.TypeFloat64, value)
		_node.UsageHours = value
	}
	if value, ok := _c.mutation.AnthropicAPIKey(); ok {
		_spec.SetField(user.FieldAnthropicAPIKey, field.TypeString, value)
		_node.AnthropicAPIKey = &value
	}
	if value, ok := _c.mutation.ClaudeOauthToken(); ok {
		_spec.SetField(user.FieldClaudeOauthToken, field.TypeString, value)
		_node.ClaudeOauthToken = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.InstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InstancesTable,
			Columns: []string{user.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ConversationsTable,
			Columns: []string{user.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
