// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/logan/cloudcode/internal/ent/conversation"
	"github.com/logan/cloudcode/internal/ent/instance"
	"github.com/logan/cloudcode/internal/ent/predicate"
	"github.com/logan/cloudcode/internal/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *UserUpdate) SetAPIKey(v string) *UserUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAPIKey(v *string) *UserUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// ClearAPIKey clears the value of the "api_key" field.
func (_u *UserUpdate) ClearAPIKey() *UserUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *UserUpdate) ClearName() *UserUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (_u *UserUpdate) SetStripeCustomerID(v string) *UserUpdate {
	_u.mutation.SetStripeCustomerID(v)
	return _u
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableStripeCustomerID(v *string) *UserUpdate {
	if v != nil {
		_u.SetStripeCustomerID(*v)
	}
	return _u
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (_u *UserUpdate) ClearStripeCustomerID() *UserUpdate {
	_u.mutation.ClearStripeCustomerID()
	return _u
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (_u *UserUpdate) SetStripeSubscriptionID(v string) *UserUpdate {
	_u.mutation.SetStripeSubscriptionID(v)
	return _u
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableStripeSubscriptionID(v *string) *UserUpdate {
	if v != nil {
		_u.SetStripeSubscriptionID(*v)
	}
	return _u
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (_u *UserUpdate) ClearStripeSubscriptionID() *UserUpdate {
	_u.mutation.ClearStripeSubscriptionID()
	return _u
}

// SetSubscriptionStatus sets the "subscription_status" field.
func (_u *UserUpdate) SetSubscriptionStatus(v string) *UserUpdate {
	_u.mutation.SetSubscriptionStatus(v)
	return _u
}

// SetNillableSubscriptionStatus sets the "subscription_status" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSubscriptionStatus(v *string) *UserUpdate {
	if v != nil {
		_u.SetSubscriptionStatus(*v)
	}
	return _u
}

// SetPlan sets the "plan" field.
func (_u *UserUpdate) SetPlan(v string) *UserUpdate {
	_u.mutation.SetPlan(v)
	return _u
}

// SetNillablePlan sets the "plan" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePlan(v *string) *UserUpdate {
	if v != nil {
		_u.SetPlan(*v)
	}
	return _u
}

// SetUsageHours sets the "usage_hours" field.
func (_u *UserUpdate) SetUsageHours(v float64) *UserUpdate {
	_u.mutation.ResetUsageHours()
	_u.mutation.SetUsageHours(v)
	return _u
}

// SetNillableUsageHours sets the "usage_hours" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUsageHours(v *float64) *UserUpdate {
	if v != nil {
		_u.SetUsageHours(*v)
	}
	return _u
}

// AddUsageHours adds value to the "usage_hours" field.
func (_u *UserUpdate) AddUsageHours(v float64) *UserUpdate {
	_u.mutation.AddUsageHours(v)
	return _u
}

// SetAnthropicAPIKey sets the "anthropic_api_key" field.
func (_u *UserUpdate) SetAnthropicAPIKey(v string) *UserUpdate {
	_u.mutation.SetAnthropicAPIKey(v)
	return _u
}

// SetNillableAnthropicAPIKey sets the "anthropic_api_key" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAnthropicAPIKey(v *string) *UserUpdate {
	if v != nil {
		_u.SetAnthropicAPIKey(*v)
	}
	return _u
}

// ClearAnthropicAPIKey clears the value of the "anthropic_api_key" field.
func (_u *UserUpdate) ClearAnthropicAPIKey() *UserUpdate {
	_u.mutation.ClearAnthropicAPIKey()
	return _u
}

// SetClaudeOauthToken sets the "claude_oauth_token" field.
func (_u *UserUpdate) SetClaudeOauthToken(v string) *UserUpdate {
	_u.mutation.SetClaudeOauthToken(v)
	return _u
}

// SetNillableClaudeOauthToken sets the "claude_oauth_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableClaudeOauthToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetClaudeOauthToken(*v)
	}
	return _u
}

// ClearClaudeOauthToken clears the value of the "claude_oauth_token" field.
func (_u *UserUpdate) ClearClaudeOauthToken() *UserUpdate {
	_u.mutation.ClearClaudeOauthToken()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddInstanceIDs adds the "instances" edge to the Instance entity by IDs.
func (_u *UserUpdate) AddInstanceIDs(ids ...int) *UserUpdate {
	_u.mutation.AddInstanceIDs(ids...)
	return _u
}

// AddInstances adds the "instances" edges to the Instance entity.
func (_u *UserUpdate) AddInstances(v ...*Instance) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInstanceIDs(ids...)
}

// AddConversationIDs adds the "conversations" edge to the Conversation entity by IDs.
func (_u *UserUpdate) AddConversationIDs(ids ...int) *UserUpdate {
	_u.mutation.AddConversationIDs(ids...)
	return _u
}

// AddConversations adds the "conversations" edges to the Conversation entity.
func (_u *UserUpdate) AddConversations(v ...*Conversation) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConversationIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearInstances clears all "instances" edges to the Instance entity.
func (_u *UserUpdate) ClearInstances() *UserUpdate {
	_u.mutation.ClearInstances()
	return _u
}

// RemoveInstanceIDs removes the "instances" edge to Instance entities by IDs.
func (_u *UserUpdate) RemoveInstanceIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveInstanceIDs(ids...)
	return _u
}

// RemoveInstances removes "instances" edges to Instance entities.
func (_u *UserUpdate) RemoveInstances(v ...*Instance) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInstanceIDs(ids...)
}

// ClearConversations clears all "conversations" edges to the Conversation entity.
func (_u *UserUpdate) ClearConversations() *UserUpdate {
	_u.mutation.ClearConversations()
	return _u
}

// RemoveConversationIDs removes the "conversations" edge to Conversation entities by IDs.
func (_u *UserUpdate) RemoveConversationIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveConversationIDs(ids...)
	return _u
}

// RemoveConversations removes "conversations" edges to Conversation entities.
func (_u *UserUpdate) RemoveConversations(v ...*Conversation) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConversationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(user.FieldAPIKey, field.TypeString, value)
	}
	if _u.mutation.APIKeyCleared() {
		_spec.ClearField(user.FieldAPIKey, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(user.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.StripeCustomerID(); ok {
		_spec.SetField(user.FieldStripeCustomerID, field.TypeString, value)
	}
	if _u.mutation.StripeCustomerIDCleared() {
		_spec.ClearField(user.FieldStripeCustomerID, field.TypeString)
	}
	if value, ok := _u.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(user.FieldStripeSubscriptionID, field.TypeString, value)
	}
	if _u.mutation.StripeSubscriptionIDCleared() {
		_spec.ClearField(user.FieldStripeSubscriptionID, field.TypeString)
	}
	if value, ok := _u.mutation.SubscriptionStatus(); ok {
		_spec.SetField(user.FieldSubscriptionStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Plan(); ok {
		_spec.SetField(user.FieldPlan, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsageHours(); ok {
		_spec.SetField(user.FieldUsageHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsageHours(); ok {
		_spec.AddField(user.FieldUsageHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AnthropicAPIKey(); ok {
		_spec.SetField(user.FieldAnthropicAPIKey, field.TypeString, value)
	}
	if _u.mutation.AnthropicAPIKeyCleared() {
		_spec.ClearField(user.FieldAnthropicAPIKey, field.TypeString)
	}
	if value, ok := _u.mutation.ClaudeOauthToken(); ok {
		_spec.SetField(user.FieldClaudeOauthToken, field.TypeString, value)
	}
	if _u.mutation.ClaudeOauthTokenCleared() {
		_spec.ClearField(user.FieldClaudeOauthToken, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InstancesTable,
			Columns: []string{user.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInstancesIDs(); len(nodes) > 0 && !_u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InstancesTable,
			Columns: []string{user.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InstancesTable,
			Columns: []string{user.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ConversationsTable,
			Columns: []string{user.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConversationsIDs(); len(nodes) > 0 && !_u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ConversationsTable,
			Columns: []string{user.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ConversationsTable,
			Columns: []string{user.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *UserUpdateOne) SetAPIKey(v string) *UserUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAPIKey(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// ClearAPIKey clears the value of the "api_key" field.
func (_u *UserUpdateOne) ClearAPIKey() *UserUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *UserUpdateOne) ClearName() *UserUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (_u *UserUpdateOne) SetStripeCustomerID(v string) *UserUpdateOne {
	_u.mutation.SetStripeCustomerID(v)
	return _u
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableStripeCustomerID(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetStripeCustomerID(*v)
	}
	return _u
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (_u *UserUpdateOne) ClearStripeCustomerID() *UserUpdateOne {
	_u.mutation.ClearStripeCustomerID()
	return _u
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (_u *UserUpdateOne) SetStripeSubscriptionID(v string) *UserUpdateOne {
	_u.mutation.SetStripeSubscriptionID(v)
	return _u
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableStripeSubscriptionID(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetStripeSubscriptionID(*v)
	}
	return _u
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (_u *UserUpdateOne) ClearStripeSubscriptionID() *UserUpdateOne {
	_u.mutation.ClearStripeSubscriptionID()
	return _u
}

// SetSubscriptionStatus sets the "subscription_status" field.
func (_u *UserUpdateOne) SetSubscriptionStatus(v string) *UserUpdateOne {
	_u.mutation.SetSubscriptionStatus(v)
	return _u
}

// SetNillableSubscriptionStatus sets the "subscription_status" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSubscriptionStatus(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetSubscriptionStatus(*v)
	}
	return _u
}

// SetPlan sets the "plan" field.
func (_u *UserUpdateOne) SetPlan(v string) *UserUpdateOne {
	_u.mutation.SetPlan(v)
	return _u
}

// SetNillablePlan sets the "plan" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePlan(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPlan(*v)
	}
	return _u
}

// SetUsageHours sets the "usage_hours" field.
func (_u *UserUpdateOne) SetUsageHours(v float64) *UserUpdateOne {
	_u.mutation.ResetUsageHours()
	_u.mutation.SetUsageHours(v)
	return _u
}

// SetNillableUsageHours sets the "usage_hours" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUsageHours(v *float64) *UserUpdateOne {
	if v != nil {
		_u.SetUsageHours(*v)
	}
	return _u
}

// AddUsageHours adds value to the "usage_hours" field.
func (_u *UserUpdateOne) AddUsageHours(v float64) *UserUpdateOne {
	_u.mutation.AddUsageHours(v)
	return _u
}

// SetAnthropicAPIKey sets the "anthropic_api_key" field.
func (_u *UserUpdateOne) SetAnthropicAPIKey(v string) *UserUpdateOne {
	_u.mutation.SetAnthropicAPIKey(v)
	return _u
}

// SetNillableAnthropicAPIKey sets the "anthropic_api_key" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAnthropicAPIKey(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAnthropicAPIKey(*v)
	}
	return _u
}

// ClearAnthropicAPIKey clears the value of the "anthropic_api_key" field.
func (_u *UserUpdateOne) ClearAnthropicAPIKey() *UserUpdateOne {
	_u.mutation.ClearAnthropicAPIKey()
	return _u
}

// SetClaudeOauthToken sets the "claude_oauth_token" field.
func (_u *UserUpdateOne) SetClaudeOauthToken(v string) *UserUpdateOne {
	_u.mutation.SetClaudeOauthToken(v)
	return _u
}

// SetNillableClaudeOauthToken sets the "claude_oauth_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableClaudeOauthToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetClaudeOauthToken(*v)
	}
	return _u
}

// ClearClaudeOauthToken clears the value of the "claude_oauth_token" field.
func (_u *UserUpdateOne) ClearClaudeOauthToken() *UserUpdateOne {
	_u.mutation.ClearClaudeOauthToken()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddInstanceIDs adds the "instances" edge to the Instance entity by IDs.
func (_u *UserUpdateOne) AddInstanceIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddInstanceIDs(ids...)
	return _u
}

// AddInstances adds the "instances" edges to the Instance entity.
func (_u *UserUpdateOne) AddInstances(v ...*Instance) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInstanceIDs(ids...)
}

// AddConversationIDs adds the "conversations" edge to the Conversation entity by IDs.
func (_u *UserUpdateOne) AddConversationIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddConversationIDs(ids...)
	return _u
}

// AddConversations adds the "conversations" edges to the Conversation entity.
func (_u *UserUpdateOne) AddConversations(v ...*Conversation) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConversationIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearInstances clears all "instances" edges to the Instance entity.
func (_u *UserUpdateOne) ClearInstances() *UserUpdateOne {
	_u.mutation.ClearInstances()
	return _u
}

// RemoveInstanceIDs removes the "instances" edge to Instance entities by IDs.
func (_u *UserUpdateOne) RemoveInstanceIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveInstanceIDs(ids...)
	return _u
}

// RemoveInstances removes "instances" edges to Instance entities.
func (_u *UserUpdateOne) RemoveInstances(v ...*Instance) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInstanceIDs(ids...)
}

// ClearConversations clears all "conversations" edges to the Conversation entity.
func (_u *UserUpdateOne) ClearConversations() *UserUpdateOne {
	_u.mutation.ClearConversations()
	return _u
}

// RemoveConversationIDs removes the "conversations" edge to Conversation entities by IDs.
func (_u *UserUpdateOne) RemoveConversationIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveConversationIDs(ids...)
	return _u
}

// RemoveConversations removes "conversations" edges to Conversation entities.
func (_u *UserUpdateOne) RemoveConversations(v ...*Conversation) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConversationIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(user.FieldAPIKey, field.TypeString, value)
	}
	if _u.mutation.APIKeyCleared() {
		_spec.ClearField(user.FieldAPIKey, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(user.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.StripeCustomerID(); ok {
		_spec.SetField(user.FieldStripeCustomerID, field.TypeString, value)
	}
	if _u.mutation.StripeCustomerIDCleared() {
		_spec.ClearField(user.FieldStripeCustomerID, field.TypeString)
	}
	if value, ok := _u.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(user.FieldStripeSubscriptionID, field.TypeString, value)
	}
	if _u.mutation.StripeSubscriptionIDCleared() {
		_spec.ClearField(user.FieldStripeSubscriptionID, field.TypeString)
	}
	if value, ok := _u.mutation.SubscriptionStatus(); ok {
		_spec.SetField(user.FieldSubscriptionStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Plan(); ok {
		_spec.SetField(user.FieldPlan, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsageHours(); ok {
		_spec.SetField(user.FieldUsageHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsageHours(); ok {
		_spec.AddField(user.FieldUsageHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AnthropicAPIKey(); ok {
		_spec.SetField(user.FieldAnthropicAPIKey, field.TypeString, value)
	}
	if _u.mutation.AnthropicAPIKeyCleared() {
		_spec.ClearField(user.FieldAnthropicAPIKey, field.TypeString)
	}
	if value, ok := _u.mutation.ClaudeOauthToken(); ok {
		_spec.SetField(user.FieldClaudeOauthToken, field.TypeString, value)
	}
	if _u.mutation.ClaudeOauthTokenCleared() {
		_spec.ClearField(user.FieldClaudeOauthToken, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InstancesTable,
			Columns: []string{user.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInstancesIDs(); len(nodes) > 0 && !_u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InstancesTable,
			Columns: []string{user.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InstancesTable,
			Columns: []string{user.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ConversationsTable,
			Columns: []string{user.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConversationsIDs(); len(nodes) > 0 && !_u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ConversationsTable,
			Columns: []string{user.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ConversationsTable,
			Columns: []string{user.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
