// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ChatMessage is the predicate function for chatmessage builders.
type ChatMessage func(*sql.Selector)

// Conversation is the predicate function for conversation builders.
type Conversation func(*sql.Selector)

// Instance is the predicate function for instance builders.
type Instance func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
